### ISSUE TITLE
(Glitchless) Confusion in induction

### ISSUE THREAD

**Issue by Fibes1** [EtaoinWu/SuperliminalASL#1]
When entering the exit sign room with 2 buttons, some runners jump out of the doorway, which seems to skip a checkpoint. Walking out the doorway normally doesn't skip it. Just thought it was something to be mentioned in the read me file, since anyone who jumps will need to remove a split. The jump can be seen at 1:17 in the glitchless wr - https://www.speedrun.com/superliminal/run/z1rqn4wm

**Comment by EtaoinWu** [comment]
Thank you for pointing out! I have added related information into the README file.
