### ISSUE TITLE
Pause on loading (and when game paused)

### ISSUE THREAD

**Issue by MicaelJarniac** [EtaoinWu/SuperliminalASL#2]
This is my first ever time using LiveSplit, so I might be missing something (took me a while to manage to get the script to work at all).

The game has a built-in speedrun timer, and it pauses automatically if you pause the game, and it also pauses during load screens.

The script provided in this repo doesn't seem to pause when loading or when the game is paused.

Is there a way to make it automatically pause on those cases?

**Comment by MicaelJarniac** [comment]
I just noticed that a few minutes ago the script was updated (replaced with another repo it seems). I'll test with this new one.

**Comment by MicaelJarniac** [comment]
Yeah, even with the new script, it still doesn't seem to pause on load or on game paused.

**Comment by EtaoinWu** [comment]
In LiveSplit, you can set your comparison to Game Time instead of Real Time (right click - Compare Against - Game Time), after which the timer would read the in-game timer. This would automatically pause during loading screen / game pause.

**Comment by MicaelJarniac** [comment]
> In LiveSplit, you can set your comparison to Game Time instead of Real Time (right click - Compare Against - Game Time), after which the timer would read the in-game timer. This would automatically pause during loading screen / game pause.

I just tried that, and it did seem to work at first (the timer paused when I paused the game), but when I finished the first level, it didn't pause during loading, and after that it also didn't pause when pausing the game.

**Comment by EtaoinWu** [comment]
What's your game's version (2019/2020/2021) and platform (EGS/Steam)? The script is not fully tested on version 2020, so there might be something going wrong here.

If the timing method is set to Game Time in LiveSplit, the timer should be the same to the in-game timer.

**Comment by EtaoinWu** [comment]
Also, you can join the [Superliminal Speedrunning](https://discord.gg/T6JbGSG) Discord server and post your problem there. Maybe someone in the community had faced a similar problem.

**Comment by MicaelJarniac** [comment]
I tested a bit again, it seems like all the way to the very end of the first level, LiveSplit and the in-game timer are in sync, and LiveSplit does pause with the game.

![Screenshot](https://i.imgur.com/MABpVf5.png)

But after I make the jump and a load screen pops up, LiveSplit doesn't pause, and after that point, pausing the game does not pause LiveSplit, so it keeps out of sync.

![Screenshot](https://i.imgur.com/BsZYviW.png)

My game is from Steam, as up-to-date as I could make it.

> File version: 2019.4.14.14309
> Product version: 2019.4.14.4208613

![Screenshot](https://i.imgur.com/SlbAVjF.png)

![Screenshot](https://i.imgur.com/3I0ZOmv.png)

From reading the file details, it seems I'm on version 2019, but I just recently purchased and installed the game, and I never downgraded it, so I don't know how accurate that is. Is the Steam version not up-to-date?

In the LiveSplit Scriptable Auto Splitter settings, it does show "Game Version: 2021".

![Screenshot](https://i.imgur.com/UJS2zkv.png)

I also have the "Individual Level" and "Split on Checkpoints" enabled.

And "Compare Against" is set to "Game Time".

![Screenshot](https://i.imgur.com/swBTpad.png)

**Comment by EtaoinWu** [comment]
You need to disable *Individual Level* in the settings if you are running the whole game. 

By the way, yes, you are running the latest version of the game. LiveSplit shows the version to be 2021, which refers to every version after 1.10.2020.12.10 (you can see this in your game options).

**Comment by MicaelJarniac** [comment]
Disabling "Individual Level" fixed it, thanks a lot!
